from enum import Enum

class GradeScope(Enum):
    USER_READ_GRADES = 1
    USER_UPDATE_GRADES = 2
    USER_CREATE_GRADES = 3 
    USER_DELETE_GRADES = 4

class ScheduleScope(Enum):
    USER_READ_SCHEDULE = 5
    USER_UPDATE_SCHEDULE = 6
    USER_CREATE_SCHEDULE = 7 
    USER_DELETE_SCHEDULE = 8

class CurriculumScope(Enum):
    USER_READ_CURRICULUM = 9
    USER_UPDATE_CURRICULUM = 10
    USER_CREATE_CURRICULUM = 11
    USER_DELETE_CURRICULUM = 12

class ClassroomScope(Enum):
    USER_READ_CLASSROOM = 13
    USER_UPDATE_CLASSROOM = 14
    USER_CREATE_CLASSROOM = 15
    USER_DELETE_CLASSROOM = 16

class NewsScope(Enum):
    USER_READ_NEWS = 17
    USER_UPDATE_NEWS = 18
    USER_CREATE_NEWS = 19
    USER_DELETE_NEWS = 20

class StudentSectionScope(Enum):
    USER_READ_STUDENT_SECTION = 21
    USER_UPDATE_STUDENT_SECTION = 22
    USER_CREATE_STUDENT_SECTION = 23
    USER_DELETE_STUDENT_SECTION = 24


