from enum import Enum

class CourseActivity(Enum):
	USER_POST_COURSE_ACTIVITY = 0
	USER_GET_COURSE_ACTIVITY = 1
	USER_DELETE_COURSE_ACTIVITY = 2
	USER_PUT_COURSE_ACTIVITY = 3

class CourseAssignment(Enum):
	USER_POST_COURSE_ASSIGNMENT = 4
	USER_GET_COURSE_ASSIGNMENT = 5
	USER_DELETE_COURSE_ASSIGNMENT = 6
	USER_PUT_COURSE_ASSIGNMENT = 7

class CourseInfo(Enum):
	USER_POST_COURSE_INFO = 8
	USER_GET_COURSE_INFO = 9
	USER_DELETE_COURSE_INFO = 10
	USER_PUT_COURSE_INFO = 11

class CourseLesson(Enum):
	USER_POST_COURSE_LESSON = 12
	USER_GET_COURSE_LESSON = 13
	USER_DELETE_COURSE_LESSON = 14
	USER_PUT_COURSE_LESSON = 15

class CourseQuiz(Enum):
	USER_POST_COURSE_QUIZ = 16
	USER_GET_COURSE_QUIZ = 17
	USER_DELETE_COURSE_QUIZ = 18
	USER_PUT_COURSE_QUIZ = 19

class CourseTask_performance(Enum):
	USER_POST_COURSE_TASK_PERFORMANCE = 20
	USER_GET_COURSE_TASK_PERFORMANCE = 21
	USER_DELETE_COURSE_TASK_PERFORMANCE = 22
	USER_PUT_COURSE_TASK_PERFORMANCE = 23
	
class StudentBalance(Enum):
	USER_POST_STUDENT_BALANCE = 24
	USER_GET_STUDENT_BALANCE = 25
	USER_DELETE_STUDENT_BALANCE = 26
	USER_PUT_STUDENT_BALANCE = 27

class StudentGrades(Enum):
	USER_POST_STUDENT_GRADES = 28
	USER_GET_STUDENT_GRADES = 29
	USER_DELETE_STUDENT_GRADES = 30
	USER_PUT_STUDENT_GRADES = 31

class StudentInfo(Enum):
	USER_POST_STUDENT_INFO = 32
	USER_GET_STUDENT_INFO = 33
	USER_DELETE_STUDENT_INFO = 34
	USER_PUT_STUDENT_INFO = 35

class StudentSchedule(Enum):
	USER_POST_STUDENT_SCHEDULE = 36
	USER_GET_STUDENT_SCHEDULE = 37
	USER_DELETE_STUDENT_SCHEDULE = 38
	USER_PUT_STUDENT_SCHEDULE = 39