name: API BRIDGE TESTING PHASE

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: API_BRIDGE
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python version
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install Latest pip
      run: python -m pip install --upgrade pip
    - name: Install Pipenv
      run: python -m pip install --upgrade pipenv wheel
    - name: Install Dependencies
      run: pipenv install
    - name: Create .env file
      run: |
        touch .env
        echo "API_VERSION=${{ secrets.API_VERSION }}" >> .env
        echo "API_SECRET_KEY=${{ secrets.API_SECRET_KEY }}" >> .env
        echo "ALGORITHM=${{ secrets.ALGORITHM }}" >> .env
        echo "ACCESS_TOKEN_EXPIRE_MINUTES=${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}" >> .env
        echo "REFRESH_TOKEN_KEYWORD=${{ secrets.REFRESH_TOKEN_KEYWORD }}" >> .env
        echo "HASH_PASSWORD=${{ secrets.HASH_PASSWORD }}" >> .env
        echo "GATEWAY_SECRET_KEY=${{ secrets.GATEWAY_SECRET_KEY }}" >> .env
        cat .env
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: PythonBuild
        path: .build/
        if-no-files-found: error
        retention-days: 1
  testing:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Download the API build 
      uses: actions/download-artifact@v3
      with: 
        name: PythonBuild
        path: .build/
    - name: Test API Bridge 
      run: pipenv run pytest -s
  deployment:
    runs-on: ubuntu-latest
    needs: testing
    steps:
    - name: deploying to cloud provider
      run: echo "For now, no cloud provider will be tested"
    
