name: API BRIDGE TESTING PHASE

on:
  push:
    branches: [ "main" ]

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: API_BRIDGE
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python version
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install Latest pip
      run: python -m pip install --upgrade pip
    - name: Install Pipenv
      run: python -m pip install --upgrade pipenv wheel
    - name: Install Dependencies
      run: pipenv install
    - name: Create .env file
      run: |
        touch .env
        echo ${{ env.ACCESS_TOKEN_EXPIRE_MINUTES }} >> .env
        echo ${{ test }} >> .env
        cat .env
    - name: Test API Bridge 
      run: pipenv run pytest -s
    
